version: "3.7"
    
services:
  app_v2:
    container_name: "docker-example-DotnetCoreV2"
    build:
      context: ./src
      dockerfile: Example.Docker.DotnetCoreV2/Dockerfile
    restart: always
  app_v3:
    container_name: "docker-example-DotnetCoreV3"
    build:
      context: ./src
      dockerfile: Example.Docker.DotnetCoreV3/Dockerfile
    restart: always
  app_v5:
    container_name: "docker-example-DotnetCoreV5"
    build:
      context: ./src
      dockerfile: Example.Docker.DotnetCoreV5/Dockerfile
    restart: always
  proxy:
    build:
       context: ./.docker/nginx
       dockerfile: Dockerfile
    restart: always
    ports:
     - "7002:82"
     - "7003:83"
     - "7005:85"
    links:
      - app_v2
      - app_v3
      - app_v5