version: "3.7"
    
services:
  app:
    container_name: "docker-example-single-app-DotnetCoreV5"
    build:
      context: ./src
      dockerfile: Example.Docker.DotnetCoreV5/Dockerfile
    restart: always
  proxy:
    container_name: "docker-example-single-app-DotnetCoreV5-nginx"
    build:
       context: ./.docker/nginx-dotnet-core-v5
       dockerfile: Dockerfile
    restart: always
    ports:
     - "8005:80"
    links:
      - app